### ISSUE TITLE
Support all memegen special characters

### ISSUE THREAD

**Issue by jasich** [jasich/memegen-ui#17]
Found on https://github.com/jacebrowning/memegen#alternate-styles

**Comment by jacebrowning** [comment]
Character escaping _could_ be added to the `POST https://memegen.link/api/templates/<key>` API so that clients don't need to do this.

**Comment by jasich** [comment]
I typed a `?` into the top text and I got back a bad response from the API so I escaped it.  I figured I might as well do all the character replacements that you list on the README just to be safe. (I think we do this in the memegen.link JavaScript already)

**Comment by jacebrowning** [comment]
I'm going to see if I can make this work: https://github.com/jacebrowning/memegen/issues/306

**Comment by jasich** [comment]
Sorry things are just starting to click for me with what you're proposing.  So your saying put whatever text into the body of a POST to create a meme and the API will respond with a 303 that has the `location` set to the image URL?

**Comment by jacebrowning** [comment]
Yes.

Though, I'm not totally sure how the response works. I doubt anyone is using that particular API so I can adjust the behavior to work for this client if needed.

**Comment by jacebrowning** [comment]
While the PR is open, you should be able to POST to this: 

https://memegen-link-pr-307.herokuapp.com/api/templates/fry

**Comment by jacebrowning** [comment]
The following is now possible:

```
$ http POST https://memegen.link/api/templates/fry top="#special characters?" bottom="underscore_ dash-" redirect=false
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
CF-RAY: 319a64a2c93e55f4-ORD
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json
Date: Sat, 31 Dec 2016 02:45:02 GMT
Server: cloudflare-nginx
Set-Cookie: __cfduid=d781f21db014b2e4492e743bc4fa77d0f1483152302; expires=Sun, 31-Dec-17 02:45:02 GMT; path=/; domain=.memegen.link; HttpOnly
Strict-Transport-Security: max-age=15552000
Transfer-Encoding: chunked
Via: 1.1 vegur
X-Content-Type-Options: nosniff

{
    "href": "/fry/~hspecial-characters~q/underscore__-dash--.jpg"
}
```
