### ISSUE TITLE
Results are still filtered after clearing search

### ISSUE THREAD

**Issue by jacebrowning** [jasich/memegen-ui#30]
# Steps

1. Search for "happy"
2. Click on a result
3. Clear the search box

## Expected

All templates are now visible.

## Actual

Only the first row of templates are visible.

**Comment by jasich** [comment]
I'm not able to reproduce this.  Can I get some more details?

**Comment by jacebrowning** [comment]
After I clear the search box, only the top row of templates appear for me:

<img width="1265" alt="screen shot 2017-01-10 at 9 32 30 pm" src="https://cloud.githubusercontent.com/assets/939501/21832885/557d27d8-d77c-11e6-9ea8-1a7ed358b6b8.png">

**Comment by jasich** [comment]
What browser are you using?

**Comment by jasich** [comment]
Ok, looks like if you delete all the characters at once (not just backspacing) then you can reproduce it.  Good catch.

**Comment by jasich** [comment]
@jacebrowning give it a try now.

**Comment by jacebrowning** [comment]
I am unable to reproduce the issue.
